import Footer from "./_components/Footer";
import Header from "./_components/Header";
import "./globals.css";
import type { Metadata } from "next";
import "ress";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
